image:
    file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
    - port: 3000
      onOpen: open-browser
    - port: 3001
      onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: >
      nvm i &&
      npm install -g pnpm &&
      pnpm install
    command: >
      nvm i &&
      npm install -g pnpm &&
      pnpm build

vscode:
  extensions:
    - unifiedjs.vscode-mdx
    - bradlc.vscode-tailwindcss
    - astro-build.astro-vscode
