language: node_js
os: linux
node_js:
  - "22"
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - npm install -g pnpm
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install