allowBuilds:
  '@parcel/watcher': set this to true or false
  '@tailwindcss/oxide': set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
