const colors = require("tailwindcss/colors");

module.exports = {
    purge: false,
    presets: [],
    darkMode: false, // or 'media' or 'class'
    theme: {
        screens: {
            // landscape: { raw: "(orientation: landscape)" },
            sm: "640px",
            md: "768px",
            lg: "1024px",
            // xl: "1280px",
            // "2xl": "1536px",
        },
        colors: {
            transparent: "transparent",
            current: "currentColor",

            primary: "#F24C4C",
            secondary: "#FFC5C5",
            vibrant: "#FFE600",

            black: colors.black,
            white: colors.white,
            gray: colors.coolGray,
            // red: colors.red,
            // yellow: colors.amber,
            // green: colors.emerald,
            // blue: colors.blue,
            // indigo: colors.indigo,
            // purple: colors.violet,
            // pink: colors.pink,
        },
        spacing: {
            // px: "1px",
            0: "0px",
            // 0.5: "0.125rem",
            1: "0.25rem",
            // 1.5: "0.375rem",
            2: "0.5rem",
            // 2.5: "0.625rem",
            3: "0.75rem",
            // 3.5: "0.875rem",
            4: "1rem",
            5: "1.25rem",
            6: "1.5rem",
            7: "1.75rem",
            8: "2rem",
            9: "2.25rem",
            10: "2.5rem",
            11: "2.75rem",
            12: "3rem",
            14: "3.5rem",
            16: "4rem",
            20: "5rem",
            24: "6rem",
            // 28: "7rem",
            32: "8rem",
            // 36: "9rem",
            40: "10rem",
            // 44: "11rem",
            // 48: "12rem",
            // 52: "13rem",
            // 56: "14rem",
            // 60: "15rem",
            // 64: "16rem",
            // 72: "18rem",
            // 80: "20rem",
            // 96: "24rem",
        },
        animation: false,
        backgroundColor: (theme) => theme("colors"),
        backgroundImage: false,
        backgroundOpacity: false,
        backgroundPosition: false,
        backgroundSize: false,
        borderColor: (theme) => ({
            DEFAULT: theme("colors.gray.200", "currentColor"),
        }),
        borderOpacity: false,
        borderRadius: {
            none: "0px",
            sm: "0.2rem",
            DEFAULT: "0.25rem",
            md: "0.375rem",
            lg: "0.5rem",
            xl: "0.75rem",
            // "2xl": "1rem",
            "3xl": "1.5rem",
            full: "9999px",
        },
        borderWidth: false,
        boxShadow: false /* {
            sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
            DEFAULT:
                "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
            md:
                "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
            lg:
                "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
            xl:
                "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
            "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
            inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
            none: "none",
        } */,
        container: {
            center: true,
        },
        cursor: {
            auto: "auto",
            default: "default",
            pointer: "pointer",
            wait: "wait",
            text: "text",
            move: "move",
            "not-allowed": "not-allowed",
        },
        divideColor: false,
        divideOpacity: false,
        divideWidth: false,
        fill: false,
        flex: {
            1: "1 1 0%",
            auto: "1 1 auto",
            initial: "0 1 auto",
            none: "none",
        },
        flexGrow: {
            0: "0",
            DEFAULT: "1",
        },
        flexShrink: false,
        fontFamily: {
            sans: ["Manrope", "sans-serif"],
            serif: ["Playfair Display", "serif"],
            title: ["Abril Fatface", "serif"],
            mono: [
                "ui-monospace",
                "SFMono-Regular",
                "Menlo",
                "Monaco",
                "Consolas",
                '"Liberation Mono"',
                '"Courier New"',
                "monospace",
            ],
        },
        fontSize: {
            xs: ["0.75rem", { lineHeight: "1rem" }],
            sm: ["0.875rem", { lineHeight: "1.25rem" }],
            base: ["1rem", { lineHeight: "1.5rem" }],
            "base-lg": ["1.025rem", { lineHeight: "1.75rem" }],
            lg: ["1.125rem", { lineHeight: "1.75rem" }],
            xl: ["1.25rem", { lineHeight: "1.75rem" }],
            "2xl": ["1.5rem", { lineHeight: "2rem" }],
            "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
            "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
            "5xl": ["3rem", { lineHeight: "1" }],
            "6xl": ["3.75rem", { lineHeight: "1" }],
            "7xl": ["4.5rem", { lineHeight: "1" }],
            "8xl": ["6rem", { lineHeight: "1" }],
            "9xl": ["8rem", { lineHeight: "1" }],
            "12xl": ["12rem", { lineHeight: "1" }],
        },
        fontWeight: {
            // thin: "100",
            // extralight: "200",
            // light: "300",
            normal: "400",
            medium: "500",
            // semibold: "600",
            bold: "700",
            extrabold: "800",
            // black: "900",
        },
        gap: (theme) => theme("spacing"),
        // gradientColorStops: false,
        gridAutoColumns: {
            auto: "auto",
            min: "min-content",
            max: "max-content",
            fr: "minmax(0, 1fr)",
        },
        gridAutoRows: {
            auto: "auto",
            min: "min-content",
            max: "max-content",
            fr: "minmax(0, 1fr)",
        },
        gridColumn: {
            auto: "auto",
            "span-1": "span 1 / span 1",
            "span-2": "span 2 / span 2",
            "span-3": "span 3 / span 3",
            "span-4": "span 4 / span 4",
            "span-5": "span 5 / span 5",
            "span-6": "span 6 / span 6",
            "span-7": "span 7 / span 7",
            "span-8": "span 8 / span 8",
            "span-9": "span 9 / span 9",
            "span-10": "span 10 / span 10",
            "span-11": "span 11 / span 11",
            "span-12": "span 12 / span 12",
            "span-full": "1 / -1",
        },
        gridColumnEnd: {
            auto: "auto",
            1: "1",
            2: "2",
            3: "3",
            4: "4",
            5: "5",
            6: "6",
            7: "7",
            8: "8",
            9: "9",
            10: "10",
            11: "11",
            12: "12",
            13: "13",
        },
        gridColumnStart: {
            auto: "auto",
            1: "1",
            2: "2",
            3: "3",
            4: "4",
            5: "5",
            6: "6",
            7: "7",
            8: "8",
            9: "9",
            10: "10",
            11: "11",
            12: "12",
            13: "13",
        },
        gridRow: {
            auto: "auto",
            "span-1": "span 1 / span 1",
            "span-2": "span 2 / span 2",
            "span-3": "span 3 / span 3",
            "span-4": "span 4 / span 4",
            "span-5": "span 5 / span 5",
            "span-6": "span 6 / span 6",
            "span-full": "1 / -1",
        },
        gridRowStart: {
            auto: "auto",
            1: "1",
            2: "2",
            3: "3",
            4: "4",
            5: "5",
            6: "6",
            7: "7",
        },
        gridRowEnd: {
            auto: "auto",
            1: "1",
            2: "2",
            3: "3",
            4: "4",
            5: "5",
            6: "6",
            7: "7",
        },
        // transformOrigin: false,
        gridTemplateColumns: {
            none: "none",
            1: "repeat(1, minmax(0, 1fr))",
            2: "repeat(2, minmax(0, 1fr))",
            3: "repeat(3, minmax(0, 1fr))",
            4: "repeat(4, minmax(0, 1fr))",
            5: "repeat(5, minmax(0, 1fr))",
            6: "repeat(6, minmax(0, 1fr))",
            7: "repeat(7, minmax(0, 1fr))",
            8: "repeat(8, minmax(0, 1fr))",
            9: "repeat(9, minmax(0, 1fr))",
            10: "repeat(10, minmax(0, 1fr))",
            11: "repeat(11, minmax(0, 1fr))",
            12: "repeat(12, minmax(0, 1fr))",
        },
        gridTemplateRows: {
            none: "none",
            1: "repeat(1, minmax(0, 1fr))",
            2: "repeat(2, minmax(0, 1fr))",
            3: "repeat(3, minmax(0, 1fr))",
            4: "repeat(4, minmax(0, 1fr))",
            5: "repeat(5, minmax(0, 1fr))",
            6: "repeat(6, minmax(0, 1fr))",
        },
        height: (theme) => ({
            auto: "auto",
            ...theme("spacing"),
            "1/2": "50%",
            "1/3": "33.333333%",
            "2/3": "66.666667%",
            "1/4": "25%",
            // "2/4": "50%",
            "3/4": "75%",
            "1/5": "20%",
            "2/5": "40%",
            "3/5": "60%",
            "4/5": "80%",
            "1/6": "16.666667%",
            // "2/6": "33.333333%",
            // "3/6": "50%",
            // "4/6": "66.666667%",
            "5/6": "83.333333%",
            full: "100%",
            screen: "100vh",
        }),
        inset: false,

        // (theme, { negative }) => ({
        //     auto: "auto",
        //     ...theme("spacing"),
        //     ...negative(theme("spacing")),
        //     "1/2": "50%",
        //     "1/3": "33.333333%",
        //     "2/3": "66.666667%",
        //     "1/4": "25%",
        //     "2/4": "50%",
        //     "3/4": "75%",
        //     full: "100%",
        //     "-1/2": "-50%",
        //     "-1/3": "-33.333333%",
        //     "-2/3": "-66.666667%",
        //     "-1/4": "-25%",
        //     "-2/4": "-50%",
        //     "-3/4": "-75%",
        //     "-full": "-100%",
        // }),
        keyframes: false,
        // {
        //     spin: {
        //         to: {
        //             transform: "rotate(360deg)",
        //         },
        //     },
        //     ping: {
        //         "75%, 100%": {
        //             transform: "scale(2)",
        //             opacity: "0",
        //         },
        //     },
        //     pulse: {
        //         "50%": {
        //             opacity: ".5",
        //         },
        //     },
        //     bounce: {
        //         "0%, 100%": {
        //             transform: "translateY(-25%)",
        //             animationTimingFunction: "cubic-bezier(0.8,0,1,1)",
        //         },
        //         "50%": {
        //             transform: "none",
        //             animationTimingFunction: "cubic-bezier(0,0,0.2,1)",
        //         },
        //     },
        // },
        letterSpacing: {
            tighter: "-0.05em",
            tight: "-0.025em",
            normal: "0em",
            wide: "0.025em",
            wider: "0.05em",
            widest: "0.1em",
        },
        lineHeight: {
            none: "1",
            tight: "1.25",
            snug: "1.375",
            normal: "1.5",
            relaxed: "1.625",
            loose: "2",
            3: ".75rem",
            4: "1rem",
            5: "1.25rem",
            6: "1.5rem",
            7: "1.75rem",
            8: "2rem",
            9: "2.25rem",
            10: "2.5rem",
        },
        listStyleType: {
            none: "none",
            disc: "disc",
            decimal: "decimal",
        },
        margin: (theme, { negative }) => ({
            auto: "auto",
            ...theme("spacing"),
            // ...negative(theme("spacing")),
        }),
        maxHeight: (theme, { breakpoints }) => ({
            ...theme("spacing"),
            full: "100%",
            screen: "100vh",
            ...breakpoints(theme("screens")),
        }),
        maxWidth: (theme, { breakpoints }) => ({
            none: "none",
            0: "0rem",
            xs: "20rem",
            sm: "24rem",
            md: "28rem",
            lg: "32rem",
            xl: "36rem",
            "2xl": "42rem",
            "3xl": "48rem",
            "4xl": "56rem",
            "5xl": "64rem",
            "6xl": "72rem",
            "7xl": "80rem",
            full: "100%",
            min: "min-content",
            max: "max-content",
            prose: "65ch",
            ...breakpoints(theme("screens")),
        }),
        minHeight: {
            0: "0px",
            full: "100%",
            screen: "100vh",
        },
        minWidth: {
            0: "0px",
            full: "100%",
            min: "min-content",
            max: "max-content",
        },
        objectPosition: false,
        // {
        //     bottom: "bottom",
        //     center: "center",
        //     left: "left",
        //     "left-bottom": "left bottom",
        //     "left-top": "left top",
        //     right: "right",
        //     "right-bottom": "right bottom",
        //     "right-top": "right top",
        //     top: "top",
        // },
        opacity: {
            0: "0",
            5: "0.05",
            10: "0.1",
            20: "0.2",
            25: "0.25",
            30: "0.3",
            40: "0.4",
            50: "0.5",
            60: "0.6",
            70: "0.7",
            75: "0.75",
            80: "0.8",
            90: "0.9",
            95: "0.95",
            100: "1",
        },
        order: false,

        // {
        //     first: "-9999",
        //     last: "9999",
        //     none: "0",
        //     1: "1",
        //     2: "2",
        //     3: "3",
        //     4: "4",
        //     5: "5",
        //     6: "6",
        //     7: "7",
        //     8: "8",
        //     9: "9",
        //     10: "10",
        //     11: "11",
        //     12: "12",
        // },
        outline: {
            none: ["2px solid transparent", "2px"],
            white: ["2px dotted white", "2px"],
            black: ["2px dotted black", "2px"],
        },
        padding: (theme) => theme("spacing"),
        placeholderColor: false, // (theme) => theme("colors"),
        placeholderOpacity: false, // (theme) => theme("opacity"),
        ringColor: (theme) => ({
            DEFAULT: theme("colors.blue.500", "#3b82f6"),
            ...theme("colors"),
        }),
        ringOffsetColor: (theme) => theme("colors"),
        ringOffsetWidth: {
            0: "0px",
            1: "1px",
            2: "2px",
            // 3: "3px",
            4: "4px",
            8: "8px",
        },
        ringOpacity: (theme) => ({
            DEFAULT: "0.5",
            ...theme("opacity"),
        }),
        ringWidth: {
            DEFAULT: "3px",
            0: "0px",
            1: "1px",
            2: "2px",
            3: "3px",
            4: "4px",
            8: "8px",
        },
        rotate: false,
        scale: false,
        skew: false,
        space: (theme, { negative }) => ({
            ...theme("spacing"),
            // ...negative(theme("spacing")),
        }),
        stroke: false,
        strokeWidth: false,
        textColor: (theme) => theme("colors"),
        textOpacity: false,
        transitionDuration: false,
        transitionDelay: false,
        transitionProperty: false,
        transitionTimingFunction: false,
        translate: false,
        width: (theme) => ({
            auto: "auto",
            ...theme("spacing"),
            "1/2": "50%",
            "1/3": "33.333333%",
            "2/3": "66.666667%",
            "1/4": "25%",
            // "2/4": "50%",
            "3/4": "75%",
            "1/5": "20%",
            "2/5": "40%",
            "3/5": "60%",
            "4/5": "80%",
            "1/6": "16.666667%",
            // "2/6": "33.333333%",
            // "3/6": "50%",
            // "4/6": "66.666667%",
            "5/6": "83.333333%",
            // "1/12": "8.333333%",
            // "2/12": "16.666667%",
            // "3/12": "25%",
            // "4/12": "33.333333%",
            "5/12": "41.666667%",
            // "6/12": "50%",
            "7/12": "58.333333%",
            // "8/12": "66.666667%",
            // "9/12": "75%",
            // "10/12": "83.333333%",
            "11/12": "91.666667%",
            full: "100%",
            screen: "100vw",
            min: "min-content",
            max: "max-content",
        }),
        zIndex: false,
    },
    corePlugins: {
        zIndex: false,
        order: false,
        objectFit: false,
        objectPosition: false,
        inset: false,
        keyframes: false,
        flexShrink: false,
        gridTemplateColumns: false,
        flexShrink: false,
        // space: false,

        // gridColumn: false,
        // gridColumnStart: false,
        // gridColumnEnd: false,
        // gridTemplateRows: false,
        // gridRow: false,
        // gridRowStart: false,
        // gridRowEnd: false,
        // gridAutoFlow: false,
        // gridAutoColumns: false,
        // gridAutoRows: false,
        // gap: false,

        fontVariantNumeric: false,
        placeholderColor: false,
        placeholderOpacity: false,
        textOpacity: false,
        backgroundAttachment: false,
        backgroundClip: false,
        backgroundOpacity: false,
        backgroundPosition: false,
        backgroundRepeat: false,
        backgroundSize: false,
        backgroundImage: false,
        gradientColorStops: false,

        borderWidth: false,
        borderColor: false,
        borderOpacity: false,
        // borderStyle: false,
        divideWidth: false,
        divideColor: false,
        divideOpacity: false,
        divideStyle: false,
        // ringWidth: false,
        // ringColor: false,
        // ringOpacity: false,
        // ringOffsetWidth: false,
        // ringOffsetColor: false,
        borderCollapse: false,
        boxShadow: false,

        // opacity: false,
        tableLayout: false,

        transitionProperty: false,
        transitionDuration: false,
        transitionTimingFunction: false,
        transitionDelay: false,
        animation: false,

        transform: false,
        transformOrigin: false,
        scale: false,
        rotate: false,
        translate: false,
        skew: false,

        appearance: false,
        resize: false,
        userSelect: false,
        fill: false,
        stroke: false,
        strokeWidth: false,
    },
    variants: {
        accessibility: ["focus-within", "focus"], // "responsive",
        alignContent: [], // "responsive"
        alignItems: [], // "responsive"
        alignSelf: [], // "responsive"
        animation: ["responsive"],
        appearance: [], // "responsive"
        backgroundAttachment: ["responsive"],
        backgroundClip: ["responsive"],
        backgroundColor: [
            // "responsive",
            // "dark",
            // "group-hover",
            // "focus-within",
            "hover",
            "focus",
        ],
        backgroundImage: [], // "responsive"
        backgroundOpacity: [
            // "responsive",
            // "group-hover",
            // "focus-within",
            // "hover",
            // "focus",
        ],
        backgroundPosition: [], // "responsive"
        backgroundRepeat: [], //"responsive"
        backgroundSize: [], // "responsive"
        borderCollapse: [], // "responsive"
        borderColor: [
            // "responsive",
            // "dark",
            // "group-hover",
            // "focus-within",
            // "hover",
            // "focus",
        ],
        borderOpacity: [
            // "responsive",
            // "group-hover",
            // "focus-within",
            // "hover",
            // "focus",
        ],
        borderRadius: [], // "responsive"
        borderStyle: [], // "responsive"
        borderWidth: [], // "responsive"
        boxShadow: [
            // "responsive",
            // "group-hover",
            // "focus-within",
            // "hover",
            // "focus",
        ],
        boxSizing: [], // "responsive"
        clear: [], // "responsive"
        container: ["responsive"],
        cursor: ["responsive"],
        display: ["responsive"],
        divideColor: [], // "responsive", "dark"
        divideOpacity: ["responsive"],
        divideStyle: ["responsive"],
        divideWidth: ["responsive"],
        fill: ["responsive"],
        flex: [], // "responsive"
        flexDirection: [], // "responsive"
        flexGrow: [], // "responsive"
        flexShrink: [], // "responsive"
        flexWrap: [], // "responsive"
        float: [], // "responsive"
        fontFamily: [], // "responsive"
        fontSize: ["responsive"],
        fontSmoothing: [], // "responsive"
        fontStyle: [], // "responsive"
        fontVariantNumeric: ["responsive"],
        fontWeight: [], // "responsive"
        gap: ["responsive"],
        gradientColorStops: ["responsive"],
        gridAutoColumns: ["responsive"],
        gridAutoFlow: ["responsive"],
        gridAutoRows: ["responsive"],
        gridColumn: ["responsive"],
        gridColumnEnd: ["responsive"],
        gridColumnStart: ["responsive"],
        gridRow: ["responsive"],
        gridRowEnd: ["responsive"],
        gridRowStart: ["responsive"],
        gridTemplateColumns: ["responsive"],
        gridTemplateRows: ["responsive"],
        height: ["responsive"], //
        inset: ["responsive"],
        justifyContent: [], // "responsive"
        justifyItems: [], // "responsive"
        justifySelf: [], // "responsive"
        letterSpacing: [], // "responsive"
        lineHeight: [], // "responsive"
        listStylePosition: [], // "responsive"
        listStyleType: [], // "responsive"
        margin: ["responsive"],
        maxHeight: [], // "responsive"
        maxWidth: [], // "responsive"
        minHeight: [], // "responsive"
        minWidth: [], // "responsive"
        objectFit: ["responsive"],
        objectPosition: ["responsive"],
        opacity: [
            // "responsive",
            // "group-hover",
            // "focus-within",
            // "hover",
            // "focus",
        ],
        order: ["responsive"],
        outline: ["focus"], // "responsive", "focus-within",
        overflow: [], // "responsive"
        overscrollBehavior: [], // "responsive"
        padding: ["responsive"],
        placeContent: [], // "responsive"
        placeItems: [], // "responsive"
        placeSelf: [], // "responsive"
        placeholderColor: ["responsive", "dark", "focus"],
        placeholderOpacity: ["responsive", "focus"],
        pointerEvents: [], // "responsive"
        position: [], // "responsive"
        resize: [], // "responsive"
        ringColor: [
            // "responsive", "dark", "focus-within",
            "focus",
        ],
        ringOffsetColor: [
            // "responsive", "dark", "focus-within",
            "focus",
        ],
        ringOffsetWidth: [
            // "responsive", "focus-within",
            "focus",
        ],
        ringOpacity: [
            // "responsive", "focus-within",
            "focus",
        ],
        ringWidth: [
            // "responsive", "focus-within",
            "focus",
        ],
        rotate: ["responsive", "hover", "focus"],
        scale: ["responsive", "hover", "focus"],
        skew: ["responsive", "hover", "focus"],
        space: ["responsive"],
        stroke: ["responsive"],
        strokeWidth: ["responsive"],
        tableLayout: ["responsive"],
        textAlign: [], // "responsive"
        textColor: [
            // "responsive",
            // "dark",
            // "group-hover",
            // "focus-within",
            "hover",
            "focus",
        ],
        textDecoration: [
            // "responsive",
            // "group-hover",
            // "focus-within",
            "hover",
            "focus",
        ],
        textOpacity: [
            "responsive",
            "group-hover",
            "focus-within",
            "hover",
            "focus",
        ],
        textOverflow: [], // "responsive"
        textTransform: [], // "responsive"
        transform: ["responsive"],
        transformOrigin: ["responsive"],
        transitionDelay: ["responsive"],
        transitionDuration: ["responsive"],
        transitionProperty: ["responsive"],
        transitionTimingFunction: ["responsive"],
        translate: ["responsive", "hover", "focus"],
        userSelect: [], // "responsive"
        verticalAlign: [], // "responsive"
        visibility: ["responsive"], //
        whitespace: [], // "responsive"
        width: [], // "responsive"
        wordBreak: [], // "responsive"
        zIndex: ["responsive", "focus-within", "focus"],
    },
    plugins: [],
};
